require 'aws'
require 'yaml'

shared_config = YAML.load_file("#{File.dirname(__FILE__)}/shared_config.yml")

ec2_instance = AWS::EC2.new(
  access_key_id: shared_config['access_key_id'],
  secret_access_key: shared_config['secret_access_key'],
).instances[shared_config['launched_instance_id']]

task default: :login

task :start do
  ec2_instance.start
end

task login: :start do
end

task push: :start do
end

task pull: :start do
end
